/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface MyComponentAttributes extends StencilHTMLAttributes {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }

  interface SwavePlayer {
    'audioUrl': string;
  }
  interface SwavePlayerAttributes extends StencilHTMLAttributes {
    'audioUrl'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'MyComponent': Components.MyComponent;
    'SwavePlayer': Components.SwavePlayer;
  }

  interface StencilIntrinsicElements {
    'my-component': Components.MyComponentAttributes;
    'swave-player': Components.SwavePlayerAttributes;
  }


  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLSwavePlayerElement extends Components.SwavePlayer, HTMLStencilElement {}
  var HTMLSwavePlayerElement: {
    prototype: HTMLSwavePlayerElement;
    new (): HTMLSwavePlayerElement;
  };

  interface HTMLElementTagNameMap {
    'my-component': HTMLMyComponentElement
    'swave-player': HTMLSwavePlayerElement
  }

  interface ElementTagNameMap {
    'my-component': HTMLMyComponentElement;
    'swave-player': HTMLSwavePlayerElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
